version: "2"

services:

  press:
      image: wordpress
      environment:
          - WORDPRESS_DB_NAME=xwnett_db1
          - WORDPRESS_DB_USER=root
          - WORDPRESS_DB_PASSWORD=secret
          - WORDPRESS_TABLE_PREFIX=site_
          - WORDPRESS_DB_HOST=mariadb
      volumes:
          - ./wpress/backup:/var/www/html
      labels:
          - "com.example.description: Wordpress Environment"
          - "version: 0.5"
          - "description: Using PHP:7-Apache-fpm build"
      links:
          - mariadb:mysql
      ports:
          - "192.168.2.2:80:80"

  mariadb:
      build: ./mariadb
      env_file: ./mariadb/common.env
      volumes_from:
        - dbdata
      labels:
          - "com.example.description: Database Environment"
          - "version: 0.5"
          - "description: Using MariaDB to host NetplayTV SQL"
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  pma:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - PMA_HOST=mariadb
    links:
      - mariadb:mysql
    ports:
      - "8181:80"

  dbdata:
      build: ./mariadb
      volumes:
        - ./mariadb/dumpfiles:/docker-entrypoint-initdb.d
      command: "true"